apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: solra
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - 10.5.100.11:9100  # master1
              - 10.5.100.12:9100  # master2
              - 10.5.100.13:9100  # master3
              - 10.5.100.21:9100  # worker1
              - 10.5.100.22:9100  # worker2
              - 10.5.100.23:9100  # worker3

      - job_name: 'kube-controller-manager'
        static_configs:
          - targets:
              - 10.5.100.11:10257
              - 10.5.100.12:10257
              - 10.5.100.13:10257
        scheme: https
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true

      - job_name: 'kube-scheduler'
        static_configs:
          - targets:
              - 10.5.100.11:10259
              - 10.5.100.12:10259
              - 10.5.100.13:10259
        scheme: https
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true

      - job_name: 'kubelet'
        static_configs:
          - targets:
              - 10.5.100.11:10250
              - 10.5.100.12:10250
              - 10.5.100.13:10250
              - 10.5.100.21:10250
              - 10.5.100.22:10250
              - 10.5.100.23:10250
        scheme: https
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true